name: LaTeX documents
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Copying all .tex and .sty files in latex/ (avoiding symlinks)
        run: |
          find latex/* -lname 'latex/*' -delete
          cp latex/*/*.tex latex/
          cp latex/*/*.sty latex/
      - name: Create handout slides
        run: |
          cd latex/
          ./make-handout
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: latex/
          root_file: |
            notebook/notebook.tex
            slides/slides.tex
            slides-handout.tex
      - name: Move compiled files to outputs folder
        run: |
          mkdir outputs/
          mv latex/*.pdf outputs/
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latex-compiled-documents
          path: outputs/

  send_to_server:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: latex-compiled-documents
          path: .
      - name: Install SSH & tools
        run: |
          sudo apt-get install -y sshpass
          sudo apt-get install -y ssh
      - name: Upload artifacts
        env:
          SSHUSER: ${{ secrets.SSHUSER }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
          SSHPATH: ${{ secrets.SSHPATH }}
          SSHPASS: ${{ secrets.SSHPASS }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no *.pdf $SSHUSER@$SSHSERVER:$SSHPATH